# -*- coding: utf-8 -*-
"""Nanas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TSecEmg-tS3EEn--vXEtnb23uHr6otd
"""

import pandas as pd

df = pd.read_csv("dataset_rgb.csv")
print(df.head())
print(df.shape)

"""# Pisahkan Fitur (RGB) dan Label (Kematangan)"""

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import joblib

X = df[['R', 'G', 'B']]
y = df['Label']

"""# Bagi Data: Training dan Testing"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""# Latih Model Machine Learning (KNN)"""

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=1)
model.fit(X_train_scaled, y_train)

for k in range(1, 11):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(f'k={k} → Accuracy: {acc:.2f}')

"""# Evaluasi Model"""

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

!pip install matplotlib seaborn

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Prediksi data test
y_pred = model.predict(X_test_scaled)

# Buat confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

# Visualisasi
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=model.classes_,
            yticklabels=model.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Contoh RGB gambar bukan nanas
sample = [[300, 129, 20]]  # RGB apel

sample_scaled = scaler.transform(sample)
prediksi = model.predict(sample_scaled)[0]

if prediksi == 'not_pineapple':
    print("Gambar tidak dikenal")
else:
    print(f"Hasil prediksi: {prediksi}")

"""# Percobaan Model"""

# Contoh data uji: RGB
sample = [[145, 130, 65]]
prediksi = model.predict(sample)
print(prediksi)

print(df.info())           # cek tipe data dan non-null
print(df.isnull().sum())   # pastikan tidak ada data kosong
print(df.duplicated().sum())  # pastikan tidak ada data duplikat
print(df.describe())       # cek distribusi nilai RGB

import joblib

# Simpan model
joblib.dump(model, 'model_knn.pkl')
joblib.dump(scaler, 'scaler_knn.pkl')